spring:
  profiles:
    active: dev
  application:
    name: activity-web

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: pre
---
spring:
  config:
    activate:
      on-profile: prod

